name: CI Build

on: [push]
jobs:
  build:
    strategy:
       fail-fast: false
       matrix:
          lua_version: [5.1, 5.2, 5.3]
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get -y install lua${{ matrix.lua_version }} liblua${{ matrix.lua_version }} lua-any
          wget http://http.us.debian.org/debian/pool/main/l/luarocks/luarocks_3.8.0+dfsg1-1_all.deb
          sudo dpkg -i luarocks_3.8.0+dfsg1-1_all.deb
          sudo luarocks install --deps-only *.rockspec
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: "Run Tests"
        run: |
          sudo luarocks make
          tools/runtests.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out