name: CI Build

on: [push]
jobs:
  build:
    strategy:
       fail-fast: true
       matrix:
          lua_version: [5.1, 5.2, 5.3, 5.4]
    name: "Build with Lua ${{ matrix.lua_version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt-get update
      - name: Install Lua ${{ matrix.lua_version }} via apt-get
        if: ${{ matrix.lua_version != 5.4 }}
        run: |
          sudo apt-get -y install lua${{ matrix.lua_version }} liblua${{ matrix.lua_version }} lua-any
      - name: Install Lua ${{ matrix.lua_version }} via action
        if: ${{ matrix.lua_version == 5.4 }}
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: Install luarocks
        run: |
          wget http://http.us.debian.org/debian/pool/main/l/luarocks/luarocks_3.8.0+dfsg1-1_all.deb
          sudo dpkg -i luarocks_3.8.0+dfsg1-1_all.deb
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: "Install Lua dependencies"
        run: |
          sudo luarocks install --deps-only *.rockspec
      - name: "Run Tests"
        run: |
          sudo luarocks make
          tools/runtests.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out