name: CI Build

on: [push]
jobs:
  build:
    strategy:
       fail-fast: true
       matrix:
          lua_version: [5.1, 5.2, 5.3, 5.4]
    name: "Build with Lua ${{ matrix.lua_version }}"
    runs-on: ubuntu-latest
    steps:
      - name: Install Lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: "Install Lua dependencies"
        run: |
          sudo luarocks install --deps-only *.rockspec
      - name: "Run Tests"
        run: |
          sudo luarocks make
          tools/runtests.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out