name: CI Build

on: [push]
jobs:
  build:
    strategy:
       fail-fast: false
       matrix:
          lua_version: [5.1, 5.2, 5.3]
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get -y install lua${{ matrix.lua_version }}
          sudo apt-get -y install liblua${{ matrix.lua_version }}
          sudo apt-get -y install luarocks
          sudo luarocks install luacheck
          sudo luarocks install luacov
          sudo luarocks install luacov-coveralls
          sudo luarocks install luaunit
          sudo luarocks install mockagne
          sudo luarocks install luasocket
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: "Run Tests"
        run: |
          sudo luarocks make
          tools/runtests.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov.report.out
          path: target/luacov-reports/luacov.report.out